#!/usr/bin/perl

# Set these for your situation
my $TARCMD = "/bin/tar cvf";
my $VERSION = "1.0";

# Init file data
my $MySettings = "$ENV{'HOME'}/.sheepbackuprc";
my $SHEEPFILE = "/usr/home/somedir/SheepShaver/MacHD.image";
my $BACKUPDIR = "/usr/home/somedir/SheepShaver/backups";
my $BACKUPUSER = "";
my $BACKUPSERVER = "";
my $BACKUPPATH = "";
my $DEBUG_MODE = "off";
my $MyEditor = $ENV{'EDITOR'};
if ($MyEditor eq "")
{
	$MyEditor = "/bin/nano";
}
my $DOSNAPSHOT = 0;
my $EditPrefs = "";

#-------------------
# No changes below here...
#-------------------

# Get if they said a option
my $CMDOPTION = shift;

sub ReadConfigFile
{
	# Check for config file
	if (-f $MySettings)
	{
		# Read in settings
		open (my $FH, "<", $MySettings) or die "Could not read settings file '$MySettings' $!";
		while (<$FH>)
		{
			chop();
			my ($Command, $Setting) = split(/=/, $_);
			if ($Command eq "backupfile")
			{
				$SHEEPFILE = $Setting;
			}
			elsif ($Command eq "backupdir")
			{
				$BACKUPDIR = $Setting;
			}
			elsif ($Command eq "backupuser")
			{
				$BACKUPUSER = $Setting;
			}
			elsif ($Command eq "backupserver")
			{
				$BACKUPSERVER = $Setting;
			}
			elsif ($Command eq "backuppath")
			{
				$BACKUPPATH = $Setting;
			}
			elsif ($Command eq "debugmode")
			{
				$DEBUG_MODE = $Setting;
			}
		}
		close($FH);
	}
	else
	{
		my $startingconfig = <<"END_MESSAGE";
# Image file to back up
backupfile=$SHEEPFILE
# Directory to store the backups in
backupdir=$BACKUPDIR
# Offsite backup user
backupuser=
# Offsite backup hostname - leave empty if you don't want a offsite backup
backupserver=
# Offsite backup path - where you want the backup stored
backuppath=
# If you want to see debugging messages set this to "on"
debugmode=off
END_MESSAGE
		# Store settings
		open (my $FH, ">", $MySettings) or die "Could not create settings file '$MySettings' $!";
		print $FH "$startingconfig\n";
		close($FH);
		system("$MyEditor $MySettings");
		print "Settings saved - please rerun backup\n";
		exit 0;
	}
}

sub PrintDebugCommand
{
	if ($DEBUG_MODE eq "off")
	{
		return;
	}
	my $PassedString = shift;
	print "About to run:\n$PassedString\n";
	print "Press Enter To Run This:";
	my $entered = <STDIN>;
}

if (defined $CMDOPTION)
{
	if ($CMDOPTION eq "snapshot")
	{
		$DOSNAPSHOT = -1;
	}
}

ReadConfigFile();

print "SheepBackup - back up your Sheepshaver Boot Volume - version $VERSION\n";
print "==================================================================\n";

if ($DOSNAPSHOT == -1)
{
        print "Running Manual Snapshot\n";
}

if (defined $CMDOPTION)
{
        if (($CMDOPTION ne "snapshot") && ($CMDOPTION ne "prefs"))
        {
                print "Unknown command line option: '$CMDOPTION'\nOnly allowed options are 'snapshot' and 'prefs'\n";
                exit 0;
        }
	if ($CMDOPTION eq "prefs")
	{
		system("$MyEditor $MySettings");
                print "Settings saved - please rerun backup\n";
                exit 0;
	}
}

my $running=`ps ax|grep SheepShaver-x86_64.AppImage|grep -v grep`;
if ($running ne "")
{
	print "Sheepshaver seems to be running. It must be shut down before running a backup.\n";
	exit 1;
}

sub SnapShotFunc
{
        print "Backing up SBBS files: ";
        if (-f "$BACKUPDIR/snapshot.tar")
        {
                unlink("$BACKUPDIR/snapshot.tar");
        }
        system("$TARCMD $BACKUPDIR/snapshot.tar $SHEEPFILE > /dev/null 2>\&1");
        print "\nBackup Completed.\n";
}

if ($DOSNAPSHOT == -1)
{
        SnapShotFunc();
        exit 0;
}

# Get if they said a option
my $CMDOPTION = shift;
if (defined $CMDOPTION)
{
        if ($CMDOPTION ne "prefs")
        {
                print "Unknown command line option: '$CMDOPTION'\nOnly allowed option is 'prefs'\n";
                exit 0;
        }
}

if ($CMDOPTION ne "")
{
	system("$MyEditor $MySettings");
	print "Settings saved - please rerun backup\n";
	exit 0;
}

if (! -d $BACKUPDIR)
{
	print "Backup dir $BACKUPDIR not found, creating...\n";
	system("mkdir -p $BACKUPDIR");
}
print "Moving existing backups: ";

if (-f "$BACKUPDIR/sheepbackup-5.tar")
{
	unlink("$BACKUPDIR/sheepbackup-5.tar")  or warn "Could not unlink $BACKUPDIR/sheepbackup-5.tar: $!";
}
if (-f "$BACKUPDIR/sheepbackup-4.tar")
{
	rename("$BACKUPDIR/sheepbackup-4.tar", "$BACKUPDIR/sheepbackup-5.tar");
}
if (-f "$BACKUPDIR/sheepbackup-3.tar")
{
	rename("$BACKUPDIR/sheepbackup-3.tar", "$BACKUPDIR/sheepbackup-4.tar");
}
if (-f "$BACKUPDIR/sheepbackup-2.tar")
{
	rename("$BACKUPDIR/sheepbackup-2.tar", "$BACKUPDIR/sheepbackup-3.tar");
}
if (-f "$BACKUPDIR/sheepbackup-1.tar")
{
	rename("$BACKUPDIR/sheepbackup-1.tar", "$BACKUPDIR/sheepbackup-2.tar");
}
print "Done\nCreating Backup: ";
system("$TARCMD $BACKUPDIR/sheepbackup-1.tar --exclude='/sbbs/ctrl/localspy*.sock' --exclude='/sbbs/ctrl/status.sock' $SHEEPFILE >/dev/null 2>\&1");
if ($BACKUPSERVER ne "")
{
	print "Offsite backup requested\n";
	print "Copying $BACKUPDIR/sheepbackup-1.tar to $BACKUPSERVER\n";
	PrintDebugCommand("rsync -avz -e ssh $BACKUPDIR/sheepbackup-1.tar $BACKUPUSER\@$BACKUPSERVER:$BACKUPPATH\n");
	system ("rsync -avz -e ssh $BACKUPDIR/sheepbackup-1.tar $BACKUPUSER\@$BACKUPSERVER:$BACKUPPATH");
}

print("Done!\n");
exit 0;
